name: Update README every 5 minutes

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: .github/workflows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make the script files executable
        run: chmod +x ./update_readme_script.sh

      - name: Update README
        run: ./update_readme_script.sh

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          cd ../../
          git add readme.md
          git commit -m "Update README" || echo "No changes to commit"
          git push
